### ISSUE TITLE
.git directory not mounted into docker container, breaks version detection

### ISSUE THREAD

**Issue by mr-c** [RalfG/python-wheels-manylinux-build#53]
https://github.com/common-workflow-language/schema_salad/runs/7371667826?check_suite_focus=true#step:7:131

Any suggestions for a workaround? I initially tried modifying my repo's `.dockerignore` but that is used for building containers, not running the `python-wheels-manylinux-build` container

**Comment by RalfG** [comment]
Hm... That's inconvenient, because the action itself does not decide what gets mounted in the container and what not. This is done by GitHub Actions itself: https://docs.github.com/en/actions/creating-actions/dockerfile-support-for-github-actions#workdir

I'm not sure how to overcome this, except for maybe cloning the repo again with this action's `pre-build-command` option? Although that is far from ideal...

Another option is to check if the more advanced [pypa/cibuildwheel](https://github.com/pypa/cibuildwheel) does work with setuptools-scm.
